language: cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
    - doxygen
    - graphviz
branches:
  only:
    - main
before_script:
  - pushd lib && ./get_deps.sh && popd
script: make
after_success:
  - doxygen Doxyfile

