/****************************************************************************
 *  DeviceNet Module 0.2                                                    *
 ****************************************************************************
 *  Author      : George D. Sotirov, gds@sd-bul.bg                          *
 *  File        : dnmsd.h                   Type        : header            *
 *  Description : Static data for the module. Vendor names and device types *
 *                names (incomplete).                                       *
 *  CVS         : $Id: dnmsd.h,v 1.2 2008/08/17 19:06:58 gsotirov Exp $
 ****************************************************************************/

#ifndef DNETMOD_STATIC_DATA_HEADER
#define DNETMOD_STATIC_DATA_HEADER 1

/* Vendor names as specified by ODVA (www.odva.org)
   Updated: 2002-12-04 07:45 GMT */
const char *VendStr[] = {
    /* Vend ID  Vendor string */
    /* 000 */   "Reserved",
    /* 001 */   "Rockwell Automation/Allen-Bradley Company, Inc.",
    /* 002 */   "Namco Controls Corp.",
    /* 003 */   "Reserved",
    /* 004 */   "Parker Hannifin Corp. (Veriflo Division)",
    /* 005 */   "Rockwell Automation/Reliance Electric",
    /* 006 */   "Schrader Bellows",
    /* 007 */   "SMC Corporation of America",
    /* 008 */   "SST Division of Woodhead Canada",
    /* 009 */   "Western Reserve Controls Inc.",
    /* 010 */   "Advanced Micro Controls Inc. (AMCI)",
    /* 011 */   "ASCO Pneumatic Controls",
    /* 012 */   "Banner Engineering Corp.",
    /* 013 */   "Belden Wire & Cable Company",
    /* 014 */   "Crouse-Hinds Molded Products",
    /* 015 */   "Reserved",
    /* 016 */   "Daniel Woodhead Co. (Woodhead Connectivity)",
    /* 017 */   "Dearborn Group Inc.",
    /* 018 */   "Reserved",
    /* 019 */   "Helm Instrument Company",
    /* 020 */   "Huron Net Works",
    /* 021 */   "Lumberg, Inc.",
    /* 022 */   "Online Development Inc. (Automation Value)",
    /* 023 */   "Vorne Industries, Inc.",
    /* 024 */   "ODVA Special Reserve",
    /* 025 */   "ACCU-Sort Systems, Inc.",
    /* 026 */   "Festo Corporation",
    /* 027 */   "Reserved",
    /* 028 */   "Crouzet Automatismes SA",
    /* 029 */   "Reserved",
    /* 030 */   "Unico, Inc.",
    /* 031 */   "Ross Controls",
    /* 032 */   "Reserved",
    /* 033 */   "Reserved",
    /* 034 */   "Hohner Corp.",
    /* 035 */   "Micro Mo Electronics, Inc.",
    /* 036 */   "MKS Instruments, Inc.",
    /* 037 */   "Yaskawa Electric America formerly Magnetek Drives",
    /* 038 */   "Whedco, Inc.",
    /* 039 */   "AVG Automation (Uticor)",
    /* 040 */   "Wago Corporation",
    /* 041 */   "Kinetics (Unit Instruments)",
    /* 042 */   "IMI Norgren Limited",
    /* 043 */   "BALLUFF, Inc.",
    /* 044 */   "Yaskawa Electric America, Inc.",
    /* 045 */   "Eurotherm Controls Inc.",
    /* 046 */   "ABB Industrial Systems",
    /* 047 */   "Omron Corporation",
    /* 048 */   "Turck, Inc.",
    /* 049 */   "Grayhill Inc.",
    /* 050 */   "Real Time Automation (C&ID)",
    /* 051 */   "Microsmith, Inc.",
    /* 052 */   "Numatics, Inc.",
    /* 053 */   "Lutze, Inc.",
    /* 054 */   "The Aro Corporation",
    /* 055 */   "Reserved",
    /* 056 */   "Softing GmbH",
    /* 057 */   "Pepperl + Fuchs",
    /* 058 */   "Spectrum Controls, Inc.",
    /* 059 */   "\"D.I.P. Inc. \"\"MKS Inst.\"\"\"",
    /* 060 */   "Applied Motion Products, Inc.",
    /* 061 */   "Sencon Inc.",
    /* 062 */   "High Country Tek",
    /* 063 */   "SWAC Automation Consult GmbH",
    /* 064 */   "Clippard Instrument Laboratory",
    /* 065 */   "ACT'L SA",
    /* 066 */   "Logical Design Group, Inc.",
    /* 067 */   "NetSafety Monitoring, Inc.",
    /* 068 */   "Cutler-Hammer Products",
    /* 069 */   "Reserved",
    /* 070 */   "RadiSys Corporation",
    /* 071 */   "Toshiba International Corp.",
    /* 072 */   "Control Technology Incorporated",
    /* 073 */   "Tait Control Systems  Ltd.",
    /* 074 */   "Hitachi, Ltd.",
    /* 075 */   "ABB Robotics Products AB",
    /* 076 */   "NKE Corporation",
    /* 077 */   "Rockwell Software, Inc.",
    /* 078 */   "Escort Memory Systems (A Datalogic Group Co.)",
    /* 079 */   "Berk-Tek/Alcatel Inc.",
    /* 080 */   "Industrial Devices Corporation",
    /* 081 */   "IXXAT automation GmbH (STZP)",
    /* 082 */   "Mitsubishi Electric Automation, Inc.",
    /* 083 */   "OPTO-22",
    /* 084 */   "Reserved",
    /* 085 */   "ECT International, Inc.",
    /* 086 */   "Horner Electric",
    /* 087 */   "Burkert Werke GmbH & Co. KG",
    /* 088 */   "Rockwell Automation/Electro-Craft Motion Control",
    /* 089 */   "Industrial Indexing Systems, Inc.",
    /* 090 */   "HMS Industrial Networks AB",
    /* 091 */   "Robicon",
    /* 092 */   "Helix Technology (Granville-Phillips)",
    /* 093 */   "Arlington Laboratory",
    /* 094 */   "Advantech Co. Ltd.",
    /* 095 */   "Square D Company",
    /* 096 */   "Digital Electronics Corp.",
    /* 097 */   "Danfoss",
    /* 098 */   "Hewlett-Packard",
    /* 099 */   "NSI SA",
    /* 100 */   "Bosch Rexroth Corporation, Pneumatics",
    /* 101 */   "Applied Materials, Inc.",
    /* 102 */   "Showa Electric Wire & Cable Co.",
    /* 103 */   "Pacific Scientific",
    /* 104 */   "Sharp Manufacturing Systems Corp.",
    /* 105 */   "Olflex Wire & Cable, Inc.",
    /* 106 */   "Reserved",
    /* 107 */   "Unitrode",
    /* 108 */   "Beckhoff Industrie Elektronik",
    /* 109 */   "National Instruments",
    /* 110 */   "Mykrolis Corporation (Millipore)",
    /* 111 */   "International Motion Controls Corp.",
    /* 112 */   "Reserved",
    /* 113 */   "SEG Kempen GmbH",
    /* 114 */   "AW Company Ltd",
    /* 115 */   "Negretti Automation Ltd.",
    /* 116 */   "MTS Systems Corp.",
    /* 117 */   "Krones, Inc",
    /* 118 */   "Molex Incorporated",
    /* 119 */   "EXOR Electronic R & D",
    /* 120 */   "SIEI S.p.A.",
    /* 121 */   "KUKA Roboter GmbH",
    /* 122 */   "Reserved",
    /* 123 */   "SEC (Samsung Electronics Co., Ltd)",
    /* 124 */   "Binary Electronics Ltd",
    /* 125 */   "Flexible Machine Controls",
    /* 126 */   "Arcom Control Systems Ltd.",
    /* 127 */   "ABB Inc. (Entrelec)",
    /* 128 */   "MAC Valves, Inc.",
    /* 129 */   "Auma Actuators Inc.",
    /* 130 */   "Toyoda Machine Works, Ltd.",
    /* 131 */   "Atlas Copco Controls SA",
    /* 132 */   "Seiberco Inc.",
    /* 133 */   "Balogh T.A.G., Corporation",
    /* 134 */   "TRSystemtechnik GmbH",
    /* 135 */   "UNIPULSE Corporation",
    /* 136 */   "White Eagle Systems Technology, Inc.",
    /* 137 */   "Rockwell Automation/DODGE",
    /* 138 */   "Conxall Corporation Inc.",
    /* 139 */   "Reserved",
    /* 140 */   "Reserved",
    /* 141 */   "Kuramo Electric Co., Ltd.",
    /* 142 */   "Creative Micro Designs",
    /* 143 */   "GE Industrial Systems",
    /* 144 */   "Leybold Vacuum GmbH",
    /* 145 */   "Siemens Energy & Automation",
    /* 146 */   "Kodensha Ltd",
    /* 147 */   "Motion Engineering, Inc.",
    /* 148 */   "Honda Engineering Co., Ltd",
    /* 149 */   "EIM Valve Controls",
    /* 150 */   "Melec Inc.",
    /* 151 */   "Sony Precision Technology Inc.",
    /* 152 */   "North American Mfg.",
    /* 153 */   "Watlow Electric Inc.",
    /* 154 */   "Japan Radio Co., Ltd",
    /* 155 */   "NADEX Co., Ltd",
    /* 156 */   "Ametek (Automation & Process Technologies)",
    /* 157 */   "Facts Engineering",
    /* 158 */   "KVASER AB",
    /* 159 */   "IDEC IZUMI Corporation",
    /* 160 */   "Mitsubishi Heavy Industries Ltd",
    /* 161 */   "Mitsubishi Electric Corporation",
    /* 162 */   "Horiba-STEC Inc.",
    /* 163 */   "esd electronic system design gmbh",
    /* 164 */   "DAIHEN Corporation",
    /* 165 */   "Tyco Valves & Controls/Keystone",
    /* 166 */   "EBARA Corporation",
    /* 167 */   "TR Electronic GmbH",
    /* 168 */   "STAS",
    /* 169 */   "Hokuyo Automatic Co., Ltd.",
    /* 170 */   "Pyramid Solutions, Inc.",
    /* 171 */   "Denso Wave Incorporated",
    /* 172 */   "HLS Hard-Line Solutions Inc",
    /* 173 */   "Caterpillar, Inc.",
    /* 174 */   "PDL Electronics Ltd.",
    /* 175 */   "AMP Incorporated",
    /* 176 */   "Red Lion Controls",
    /* 177 */   "ANELVA Corporation",
    /* 178 */   "Toyo Denki Seizo KK",
    /* 179 */   "Sanyo Denki Co., Ltd.",
    /* 180 */   "Aera Japan Ltd.",
    /* 181 */   "Pilz GmbH & Co",
    /* 182 */   "Marsh Bellofram-Bellofram PCD Division",
    /* 183 */   "Reserved",
    /* 184 */   "M•SYSTEM Co. Ltd.",
    /* 185 */   "Nissin Electric Co., Ltd",
    /* 186 */   "Hitachi Metals, Ltd.",
    /* 187 */   "Oriental Motor Company",
    /* 188 */   "A&D Co., Ltd",
    /* 189 */   "Phasetronics, Inc.",
    /* 190 */   "Cummins Engine Company",
    /* 191 */   "Deltron Inc.",
    /* 192 */   "Geneer Corporation",
    /* 193 */   "Anatol Automation, Inc.",
    /* 194 */   "Sterling Controls",
    /* 195 */   "Reserved",
    /* 196 */   "Medar, Inc.",
    /* 197 */   "Comdel Inc.",
    /* 198 */   "Advanced Energy Industries, Inc.",
    /* 199 */   "Reserved",
    /* 200 */   "Daiden Co., Ltd",
    /* 201 */   "CKD Corporation",
    /* 202 */   "Toyo Electric Corporation",
    /* 203 */   "HM Computing Ltd.",
    /* 204 */   "AuCom Electronics Ltd",
    /* 205 */   "Shinko Electric Co., Ltd",
    /* 206 */   "Vector Informatik GmbH",
    /* 207 */   "ASAP, Inc.",
    /* 208 */   "Moog Inc.",
    /* 209 */   "Contemporary Controls",
    /* 210 */   "Tokyo Sokki Kenkyujo Co., Ltd",
    /* 211 */   "Schenck-AccuRate, Inc.",
    /* 212 */   "The Oilgear Company",
    /* 213 */   "Reserved",
    /* 214 */   "ASM Japan K.K.",
    /* 215 */   "HIRATA Corp.",
    /* 216 */   "SUNX Limited",
    /* 217 */   "Meidensha Corporation",
    /* 218 */   "Sankyo Seiki Mfg. Co., Ltd",
    /* 219 */   "KAMRO Corp.",
    /* 220 */   "Nippon System Development Co., Ltd",
    /* 221 */   "EBARA Technologies Inc.",
    /* 222 */   "JP Tech",
    /* 223 */   "Reserved",
    /* 224 */   "SG Co., Ltd",
    /* 225 */   "Vaasa Institute of Technology",
    /* 226 */   "ENI (Electronic Navigation Industry)",
    /* 227 */   "Tateyama System Laboratory Co., Ltd.",
    /* 228 */   "QLOG Corporation",
    /* 229 */   "Matric Limited Inc.",
    /* 230 */   "NSD Corporation",
    /* 231 */   "Oildyne",
    /* 232 */   "Sumitomo Wiring Systems, Ltd.",
    /* 233 */   "Group3 Technology Ltd",
    /* 234 */   "CTI Cryogenics",
    /* 235 */   "POLSYS CORP",
    /* 236 */   "Ampere Inc.",
    /* 237 */   "NESLAB Instruments, Inc.",
    /* 238 */   "Simplatroll Ltd",
    /* 239 */   "Pacific Scientific Instruments",
    /* 240 */   "Reserved",
    /* 241 */   "Leading Edge Design",
    /* 242 */   "Humphrey Products",
    /* 243 */   "Schneider Automation, Inc.",
    /* 244 */   "Westlock Controls Corp.",
    /* 245 */   "Nihon Weidmuller Co., Ltd",
    /* 246 */   "Brooks Instrument (div of Emerson)",
    /* 247 */   "Electroglas Inc.",
    /* 248 */   "Moeller ElectroniX",
    /* 249 */   "Varian Vacuum Products",
    /* 250 */   "Yokogawa Electric Corp/IT Controller Division",
    /* 251 */   "Electrical Design Daiyu Co., Ltd",
    /* 252 */   "Omron Software Co., Ltd.",
    /* 253 */   "BOC Edwards",
    /* 254 */   "Control Technology Corporation",
    /* 255 */   "Bosch Rexroth",
    /* 256 */   "InterlinkBT LLC",
    /* 257 */   "Control Techniques PLC",
    /* 258 */   "Hardy Instruments, Inc.",
    /* 259 */   "LG Industrial System Co., Ltd.",
    /* 260 */   "E.O.A Systems Inc.",
    /* 261 */   "Reserved",
    /* 262 */   "New Cosmos Electric Co., Ltd.",
    /* 263 */   "Sense Eletronica LTDA.",
    /* 264 */   "Xycom, Inc.",
    /* 265 */   "Baldor Electric",
    /* 266 */   "Brooks Automation Canada",
    /* 267 */   "Patlite Corporation",
    /* 268 */   "BCE-Elektronik GbRmbH",
    /* 269 */   "Mogami Wire & Cable Corporation",
    /* 270 */   "Weltronics/Technitron Corp.",
    /* 271 */   "Oven Industries, Inc.",
    /* 272 */   "Deutschmann Automation GmbH",
    /* 273 */   "ICP Panel-Tec, Inc.",
    /* 274 */   "Bray Controls USA",
    /* 275 */   "Lantronix, Inc. (Synergetic Micro Sys.)",
    /* 276 */   "Status Technologies",
    /* 277 */   "Trio Motion Tech Ltd",
    /* 278 */   "Sherrex Systems Ltd",
    /* 279 */   "Adept Technology, Inc.",
    /* 280 */   "Spang Power Electronics",
    /* 281 */   "Reserved",
    /* 282 */   "Acrosser Technology Co. Ltd",
    /* 283 */   "Hilscher GmbH",
    /* 284 */   "IMAX Corporation",
    /* 285 */   "Electronic Innovation, Inc. (Falter Engineering)",
    /* 286 */   "Netlogic Inc.",
    /* 287 */   "Bosch Rexroth Corporation, Indramat",
    /* 288 */   "Elektronik-Systeme Lauer GmbH",
    /* 289 */   "Reserved",
    /* 290 */   "Murata Machinery, Ltd.",
    /* 291 */   "MTT Company Ltd.",
    /* 292 */   "Kanematsu Semiconductor Corp.",
    /* 293 */   "Takehishi Electric Sales Co.",
    /* 294 */   "Tokyo Electron Device Limited",
    /* 295 */   "PFU Limited",
    /* 296 */   "Hakko Automation Co., Ltd.",
    /* 297 */   "Advanet Inc.",
    /* 298 */   "Tokyo Electron Yamanashi Limited",
    /* 299 */   "Reserved",
    /* 300 */   "Shinagawa Electric Wire Co. Ltd.",
    /* 301 */   "Yokogawa M&C Corporation",
    /* 302 */   "KONAN Electric Co., Ltd",
    /* 303 */   "Binar Elektronik AB",
    /* 304 */   "The Furukawa Electric Co.",
    /* 305 */   "Cooper Energy Services",
    /* 306 */   "Schleicher GmbH & Co.",
    /* 307 */   "Hirose Electric Co., Ltd",
    /* 308 */   "Western Servo Design Inc.",
    /* 309 */   "Reserved",
    /* 310 */   "AMSC. Co., Ltd",
    /* 311 */   "Towa Shoko Co., Ltd",
    /* 312 */   "Kyopal Co., Ltd",
    /* 313 */   "Extron Co.",
    /* 314 */   "Wieland Electric GmbH",
    /* 315 */   "SEW Eurodrive GmbH",
    /* 316 */   "Aera Corporation",
    /* 317 */   "STA Reutlingen",
    /* 318 */   "Reserved",
    /* 319 */   "Fuji Electric Co., Ltd.",
    /* 320 */   "Gestra GmbH",
    /* 321 */   "Gill Technologies Inc.",
    /* 322 */   "ifm efector, inc.",
    /* 323 */   "Reserved",
    /* 324 */   "IDEACOD-Hohner AUTOMATION S.A.",
    /* 325 */   "CommScope, Inc.",
    /* 326 */   "GE Fanuc Automation North America, Inc.",
    /* 327 */   "Matsushita Electric Industrial Co., Ltd",
    /* 328 */   "Okaya Electronics Corporation",
    /* 329 */   "KASHIYAMA Industries, Ltd.",
    /* 330 */   "JVC",
    /* 331 */   "Interface Corporation",
    /* 332 */   "Grape Systems Inc.",
    /* 333 */   "Kinkei System Corporation",
    /* 334 */   "Mitsubishi Cable Industries Ltd.",
    /* 335 */   "Toshiba IT & Control Systems Corporation",
    /* 336 */   "Sanyo Machine Works, Ltd.",
    /* 337 */   "Vansco Electronics Ltd.",
    /* 338 */   "Dart Container Corp.",
    /* 339 */   "Livingston & Co., Inc.",
    /* 340 */   "Alfa Laval LKM as",
    /* 341 */   "British Federal Ltd.",
    /* 342 */   "Bekaert Engineering NV",
    /* 343 */   "Ferran  Scientific Inc.",
    /* 344 */   "KEBA Automation Ges. M.b.H. &Co.",
    /* 345 */   "Reserved",
    /* 346 */   "The Lincoln Electric Company",
    /* 347 */   "Reserved",
    /* 348 */   "Berger Lahr GmbH 3333",
    /* 349 */   "Reserved",
    /* 350 */   "Federal Signal Corporation",
    /* 351 */   "Reserved",
    /* 352 */   "Reserved",
    /* 353 */   "Reserved",
    /* 354 */   "FRABA Posital GmbH",
    /* 355 */   "Reserved",
    /* 356 */   "Fanuc Robotics North America, Inc.",
    /* 357 */   "O. G. Line S.A.",
    /* 358 */   "Surface Combustion, Inc.",
    /* 359 */   "Redwood MicroSystems, Inc.",
    /* 360 */   "AILES Electronics Ind. Co, Ltd.",
    /* 361 */   "Reserved",
    /* 362 */   "Particle Measuring Systems, Inc.",
    /* 363 */   "Reserved",
    /* 364 */   "Mink Consulting Inc.",
    /* 365 */   "BITS Co., Ltd",
    /* 366 */   "Japan Aviation Electronics Industry Ltd",
    /* 367 */   "Keyence Corporation",
    /* 368 */   "Kuroda Precision Industries Ltd.",
    /* 369 */   "Mitsubishi Electric Semiconductor Application",
    /* 370 */   "Nippon Seisen Cable, Ltd.",
    /* 371 */   "Omron ASO Co., Ltd",
    /* 372 */   "Seiko Seiki Co., Ltd.",
    /* 373 */   "Sumitomo Heavy Industries, Ltd.",
    /* 374 */   "Tango Computer Service Corporation",
    /* 375 */   "Technology Service, Inc.",
    /* 376 */   "Toshiba Information Systems (Japan) Corporation",
    /* 377 */   "Toshiba Mie Plant",
    /* 378 */   "Toyooki Kogyo Co., Ltd.",
    /* 379 */   "XEBEC",
    /* 380 */   "Madison Cable Corporation",
    /* 381 */   "Hitachi Engineering & Services Co., Ltd",
    /* 382 */   "TEM-TECH Lab Co., Ltd",
    /* 383 */   "International Laboratory Corporation",
    /* 384 */   "Dyadic Systems Co., Ltd.",
    /* 385 */   "SETO Electronics Industry Co., Ltd",
    /* 386 */   "Tokyo Electron Kyushu Limited",
    /* 387 */   "KEI System Co., Ltd",
    /* 388 */   "Kasuga Electric Works",
    /* 389 */   "Asahi Engineering Co., Ltd",
    /* 390 */   "Contrex Inc.",
    /* 391 */   "Paradigm Controls Ltd.",
    /* 392 */   "Comas S.p.A.",
    /* 393 */   "Ohm Electric Co., Ltd.",
    /* 394 */   "RKC Instrument Inc.",
    /* 395 */   "Suzuki Motor Corporation",
    /* 396 */   "Custom Servo Motors Inc.",
    /* 397 */   "PACE Control Systems",
    /* 398 */   "Selectron Lyss AG",
    /* 399 */   "Reserved",
    /* 400 */   "LINTEC Co., Ltd",
    /* 401 */   "Hitachi Cable Ltd.",
    /* 402 */   "BUSWARE Direct",
    /* 403 */   "Holec Holland N.V.",
    /* 404 */   "VAT Vakuumventile AG",
    /* 405 */   "Scientific Technologies Incorporated",
    /* 406 */   "Alfa Instrumentos Eletronicos Ltda",
    /* 407 */   "TWK Elektronik GmbH",
    /* 408 */   "ABB Welding Systems AB",
    /* 409 */   "BYSTRONIC Maschinen AG",
    /* 410 */   "Kimura Electric Co., Ltd",
    /* 411 */   "Nissei Plastic Industrial Co., Ltd",
    /* 412 */   "Hitachi Naka Electronics Co. Ltd.",
    /* 413 */   "Kistler-Morse Corporation",
    /* 414 */   "Proteous Industries Inc.",
    /* 415 */   "Reserved",
    /* 416 */   "Nordson Corporation",
    /* 417 */   "Rapistan Systems",
    /* 418 */   "LP-Elektronik GmbH",
    /* 419 */   "GERBI & FASE S.p.A (Fase Saldatura)",
    /* 420 */   "Reserved",
    /* 421 */   "Z-World Engineering",
    /* 422 */   "Honda R&D Co., Ltd.",
    /* 423 */   "Bionics Instrument Co., Ltd.",
    /* 424 */   "Teknic, Inc.",
    /* 425 */   "Reserved",
    /* 426 */   "Reserved",
    /* 427 */   "Ryco Graphic Manufacturing Inc.",
    /* 428 */   "Giddings & Lewis, Inc.",
    /* 429 */   "Koganei Corporation",
    /* 430 */   "Reserved",
    /* 431 */   "Nichigoh Communication Electric Wire Co., Ltd.",
    /* 432 */   "Nippon Motorola Ltd",
    /* 433 */   "Fujikura Ltd.",
    /* 434 */   "AD Link Technology Inc.",
    /* 435 */   "StoneL Corporation",
    /* 436 */   "Computer Optical Products, Inc.",
    /* 437 */   "CONOS Inc.",
    /* 438 */   "Erhardt + Leimer GmbH",
    /* 439 */   "UNIQUE Co. Ltd.",
    /* 440 */   "Roboticsware, Inc.",
    /* 441 */   "Nachi Fujikoshi Corporation",
    /* 442 */   "Hengstler GmbH",
    /* 443 */   "Reserved",
    /* 444 */   "SUNNY GIKEN Inc.",
    /* 445 */   "Lenze GmbH & Co KG",
    /* 446 */   "CD Systems B.V.",
    /* 447 */   "FMT/Aircraft Gate Support Systems AB",
    /* 448 */   "Axiomatic Technologies Corporation",
    /* 449 */   "Embedded System Products, Inc.",
    /* 450 */   "AMC Technologies Corporation",
    /* 451 */   "Mencom Corporation",
    /* 452 */   "Danaher Motion (Kollmorgen Ind. Drives)",
    /* 453 */   "Matsushita Welding Systems Co.,Ltd.",
    /* 454 */   "Dengensha Mfg. Co. Ltd.",
    /* 455 */   "Quinn Systems Ltd.",
    /* 456 */   "Tellima Technology Ltd",
    /* 457 */   "MDT, Software",
    /* 458 */   "Taiwan Keiso Co., Ltd",
    /* 459 */   "Pinnacle Systems",
    /* 460 */   "Ascom Hasler Mailing Sys",
    /* 461 */   "INSTRUMAR Limited",
    /* 462 */   "Reserved",
    /* 463 */   "Reserved",
    /* 464 */   "Huttinger Elek. GmbH + Co. KG",
    /* 465 */   "OCM Technology Inc.",
    /* 466 */   "Professional Supply Inc.",
    /* 467 */   "Control Solutions",
    /* 468 */   "IVO GmbH & Co.",
    /* 469 */   "Worcester Controls Corporation",
    /* 470 */   "Pyramid Technical Consultants, Inc.",
    /* 471 */   "Eilersen Electric A/S",
    /* 472 */   "Apollo Fire Detectors Limited",
    /* 473 */   "Avtron Manufacturing, Inc.",
    /* 474 */   "Yazaki Parts Co., Ltd.",
    /* 475 */   "Tokyo Keiso Co., Ltd.",
    /* 476 */   "Daishowa Swiki Co., Ltd.",
    /* 477 */   "Kojima Instruments Inc.",
    /* 478 */   "Shimadzu Corporation",
    /* 479 */   "Tatsuta Electric Wire & Cable Co., Ltd.",
    /* 480 */   "MECS Corporation",
    /* 481 */   "Tahara Electric",
    /* 482 */   "Koyo Electronics",
    /* 483 */   "Clever Devices",
    /* 484 */   "GCD Hardware & Software GmbH",
    /* 485 */   "Reserved",
    /* 486 */   "Miller Electric Mfg Co.",
    /* 487 */   "GEA Tuchenhagen GmbH",
    /* 488 */   "Riken Keiki Co., Ltd.",
    /* 489 */   "Keisokugiken Corporation",
    /* 490 */   "Fuji Machine Mfg. Co., Ltd",
    /* 491 */   "Muramiq, Ltd.",
    /* 492 */   "Nidec-Shimpo Corp.",
    /* 493 */   "UTEC Corporation",
    /* 494 */   "Sanyo Electric Co. Ltd.",
    /* 495 */   "Harmo Co. Ltd.",
    /* 496 */   "Reserved",
    /* 497 */   "Okano Electric Wire Co. Ltd",
    /* 498 */   "Shimaden Co. Ltd.",
    /* 499 */   "Teddington Controls Ltd",
    /* 500 */   "Control Logic Inc.",
    /* 501 */   "VIPA GmbH",
    /* 502 */   "Warwick Manufacturing Group",
    /* 503 */   "Danaher Controls",
    /* 504 */   "Integrated Systems Engineering, Inc.",
    /* 505 */   "Reserved",
    /* 506 */   "American Science & Engineering",
    /* 507 */   "Accutron Technologies Inc.",
    /* 508 */   "Norcott Technologies Ltd",
    /* 509 */   "TB Woods, Inc",
    /* 510 */   "Proportion-Air, Inc.",
    /* 511 */   "Max Stegmann GmbH",
    /* 512 */   "Chorum Technologies, Inc.",
    /* 513 */   "Edwards Signaling",
    /* 514 */   "Sumitomo Metal Industries, Ltd",
    /* 515 */   "Cosmo Instruments Co., Ltd.",
    /* 516 */   "Denshosha Co., Ltd.",
    /* 517 */   "Kaijo Corp.",
    /* 518 */   "Michiproducts Co., Ltd.",
    /* 519 */   "Miura Corporation",
    /* 520 */   "TG Information Network Co., Ltd.",
    /* 521 */   "Fujikin , Inc.",
    /* 522 */   "Estic Corp.",
    /* 523 */   "GS Hydraulic Sales",
    /* 524 */   "Leuze electronic GmbH",
    /* 525 */   "MTE Limited",
    /* 526 */   "Hyde Park Electronics, Inc.",
    /* 527 */   "Pfeiffer Vacuum GmbH",
    /* 528 */   "Reserved",
    /* 529 */   "OKUMA Corporation FA System Division",
    /* 530 */   "NSK Corporation",
    /* 531 */   "Kokusai Electric Co., Ltd.",
    /* 532 */   "SHINKO TECHNOS Co., Ltd.",
    /* 533 */   "Itoh Electric Co., Ltd.",
    /* 534 */   "Colorado Flow Tech Inc.",
    /* 535 */   "Love Controls Division/Dwyer Instruments",
    /* 536 */   "Alstom Drives and Controls",
    /* 537 */   "Reserved",
    /* 538 */   "Tescom Corporation",
    /* 539 */   "kws Computersysteme GmbH",
    /* 540 */   "Atlas Copco Controls UK",
    /* 541 */   "MAXTEC International",
    /* 542 */   "Autojet Technologies",
    /* 543 */   "Prima Electronics S.p.A.",
    /* 544 */   "PMA GmbH",
    /* 545 */   "Shimafuji Electric Co., Ltd",
    /* 546 */   "Oki Electric Industry Co., Ltd",
    /* 547 */   "Kyushu Matsushita Electric Co., Ltd",
    /* 548 */   "Nihon Electric Wire & Cable Co., Ltd",
    /* 549 */   "Tsuken Electric Ind Co., Ltd",
    /* 550 */   "Tamadic Co.",
    /* 551 */   "MAATEL SA",
    /* 552 */   "OKUMA America",
    /* 553 */   "Emerson Motion Control",
    /* 554 */   "TPC Wire & Cable",
    /* 555 */   "ATI Industrial Automation",
    /* 556 */   "Microcontrol (Australia) Pty Ltd",
    /* 557 */   "Serra Soldadura, S.A.",
    /* 558 */   "Southwest Research Institute",
    /* 559 */   "Cabinplant International",
    /* 560 */   "GWT/Global Weighing Technologies GmbH",
    /* 561 */   "COMAU  Robotica",
    /* 562 */   "Phoenix Contact",
    /* 563 */   "Yokogawa MAT Corporation",
    /* 564 */   "asahi sangyo co., ltd.",
    /* 565 */   "Valcom Co., Ltd.",
    /* 566 */   "Akita Myotoku Ltd.",
    /* 567 */   "OBARA Corp.",
    /* 568 */   "Suetron Electronic GmbH",
    /* 569 */   "AG-E Szamitastechnikal KFT",
    /* 570 */   "Serck Controls Limited",
    /* 571 */   "Fairchild Industrial Products Company",
    /* 572 */   "ARO S.A.",
    /* 573 */   "M2C GmbH",
    /* 574 */   "Shin Caterpillar Mitsubishi Ltd.",
    /* 575 */   "Santest Co., Ltd.",
    /* 576 */   "Cosmotechs Co., Ltd.",
    /* 577 */   "Hitachi Electric Systems",
    /* 578 */   "Smartscan Ltd",
    /* 579 */   "applicom international",
    /* 580 */   "Athena Controls Incorporated",
    /* 581 */   "Syron Engineering & Manufacturing, Inc.",
    /* 582 */   "Asahi Optical Co., Ltd.",
    /* 583 */   "Sansha Electric Mfg. Co.,Ltd.",
    /* 584 */   "Nikki Denso Co., Ltd.",
    /* 585 */   "Star Micronics, Co., Ltd.",
    /* 586 */   "Ecotecnia Socirtat Corp.",
    /* 587 */   "AC Technology Corp.",
    /* 588 */   "West Instruments Limited",
    /* 589 */   "NTI Limited",
    /* 590 */   "Reserved",
    /* 591 */   "FANUC Ltd.",
    /* 592 */   "Hearn-Gu Lee",
    /* 593 */   "Reserved",
    /* 594 */   "Orion Machinery Co., Ltd.",
    /* 595 */   "ExtraTech Corp.",
    /* 596 */   "Wire-Pro, Inc.",
    /* 597 */   "Beijing Huakong Technology Co. Ltd.",
    /* 598 */   "Yokoyama Shokai Co., Ltd.",
    /* 599 */   "Toyogiken Co., Ltd.",
    /* 600 */   "Coester Equipamentos Eletronicos Ltda.",
    /* 601 */   "Kawasaki Heavy Industries, Ltd.",
    /* 602 */   "Electroplating Engineers of Japan Ltd.",
    /* 603 */   "Robox S.p.a.",
    /* 604 */   "Spraying Systems Company",
    /* 605 */   "Benshaw Inc.",
    /* 606 */   "ZPA-DP A.S.",
    /* 607 */   "Wired Rite Systems",
    /* 608 */   "Tandis Research, Inc.",
    /* 609 */   "Eurotherm Antriebstechnik GmbH",
    /* 610 */   "ULVAC, Inc.",
    /* 611 */   "DYNAX Corporation",
    /* 612 */   "Nor-Cal Products, Inc.",
    /* 613 */   "Aros Electronics AB",
    /* 614 */   "Jun-Tech Co., Ltd.",
    /* 615 */   "HAN-MI Co. Ltd.",
    /* 616 */   "SungGi Internet Co.,  Ltd.",
    /* 617 */   "Hae Pyung Electronics Research Institute",
    /* 618 */   "Milwaukee Electronics",
    /* 619 */   "OBERG Industries",
    /* 620 */   "Parker Hannifin/Compumotor Division",
    /* 621 */   "TECHNO DIGITAL CORPORATION",
    /* 622 */   "network supply Co., Ltd.",
    /* 623 */   "Union Electronics Co., Ltd.",
    /* 624 */   "Reserved",
    /* 625 */   "Rockwell Automation-Sprecher+Schuh",
    /* 626 */   "Matsushita Electric Industrial Co., Ltd/Motor Company",
    /* 627 */   "Reserved",
    /* 628 */   "JEONGIL INTERCOM CO., LTD",
    /* 629 */   "Interroll Corp.",
    /* 630 */   "Hubbell Wiring Device-Kellems (Delaware)",
    /* 631 */   "Intelligent Motion Systems",
    /* 632 */   "Shanghai Aton Electric Co., Ltd",
    /* 633 */   "INFICON AG",
    /* 634 */   "Hirschmann, Inc.",
    /* 635 */   "Reserved",
    /* 636 */   "YAMAHA Motor Co. Ltd.",
    /* 637 */   "aska corporation",
    /* 638 */   "Woodhead Connectivity ",
    /* 639 */   "Trimble Navigation Limited (Spectra Precision AB)",
    /* 640 */   "Murrelektronik GmbH",
    /* 641 */   "Creatrix Labs, Inc.",
    /* 642 */   "TopWorx",
    /* 643 */   "Kumho Industrial Co., Ltd.",
    /* 644 */   "Wind River Systems, Inc.",
    /* 645 */   "Bihl & Wiedemann GmbH",
    /* 646 */   "Harmonic Drive Systems Inc.",
    /* 647 */   "Rikei Corporation",
    /* 648 */   "BL Autotec, Ltd.",
    /* 649 */   "Hana Information & Technology Co., Ltd.",
    /* 650 */   "Seoil Electric Co., Ltd.",
    /* 651 */   "Fife Corporation",
    /* 652 */   "Shanghai Electrical Apparatus Research Institute",
    /* 653 */   "UniControls as",
    /* 654 */   "Parasense Development Centre",
    /* 655 */   "Mainco",
    /* 656 */   "Reserved",
    /* 657 */   "Six Tau S.p.A.",
    /* 658 */   "Aucos GmbH",
    /* 659 */   "Rotork Controls Ltd.",
    /* 660 */   "Automationdirect.com",
    /* 661 */   "Thermo BLH",
    /* 662 */   "System Controls, Ltd.",
    /* 663 */   "Univer S.p.A.",
    /* 664 */   "Tenta Technology",
    /* 665 */   "Lika Electronic SNC",
    /* 666 */   "Mettler-Toledo",
    /* 667 */   "DXL USA, Inc.",
    /* 668 */   "Rockwell Automation/Entek IRD Intl.",
    /* 669 */   "Nippon Otis Elevator Company",
    /* 670 */   "Sinano Electric, Co., Ltd.",
    /* 671 */   "Sony Manufacturing Systems",
    /* 672 */   "Reserved",
    /* 673 */   "Contec Co.,Ltd.",
    /* 674 */   "Reserved",
    /* 675 */   "Controlweigh",
    /* 676 */   "Reserved",
    /* 677 */   "Fincor Electronics",
    /* 678 */   "Cognex Corporation",
    /* 679 */   "Qualiflow",
    /* 680 */   "Weidmuller Inc.",
    /* 681 */   "Morinaga Milk Industry Co., Ltd.",
    /* 682 */   "Takagi Industrial Co., Ltd.",
    /* 683 */   "Wittenstein Ternary Co., Ltd.",
    /* 684 */   "Sena Technologies, Inc.",
    /* 685 */   "Marathon Ltd.",
    /* 686 */   "APV Systems",
    /* 687 */   "Creator Teknisk Utvedkling AB",
    /* 688 */   "Reserved",
    /* 689 */   "Mibu Denki Industrial Co., Ltd.",
    /* 690 */   "Takamatsu Machineer Section",
    /* 691 */   "Startco Engineering Ltd.",
    /* 692 */   "Reserved",
    /* 693 */   "Holjeron",
    /* 694 */   "ALCATEL High Vacuum Technology",
    /* 695 */   "Taesan LCD Co., Ltd.",
    /* 696 */   "POSCON",
    /* 697 */   "VMIC",
    /* 698 */   "Matsushita Electric Works, Ltd.",
    /* 699 */   "IAI Corporation",
    /* 700 */   "Horst GmbH",
    /* 701 */   "MicroControl GmbH & Co.",
    /* 702 */   "Leine & Linde AB",
    /* 703 */   "Hastings Instruments",
    /* 704 */   "EC Elettronica Srl",
    /* 705 */   "VIT Software HB",
    /* 706 */   "Bronkhorst High-Tech B.V.",
    /* 707 */   "Optex Co.,Ltd.",
    /* 708 */   "Yosio Electronic Co.",
    /* 709 */   "Terasaki Electric Co., Ltd.",
    /* 710 */   "Sodick Co., Ltd.",
    /* 711 */   "MTS Systems Corporation-Automation Division",
    /* 712 */   "Mesa Systemtechnik",
    /* 713 */   "SHIN HO SYSTEM Co., Ltd.",
    /* 714 */   "Kokusai Denki Engineering Co., Ltd.",
    /* 715 */   "Loreme",
    /* 716 */   "SAB Brockskes GmbH & Co. KG",
    /* 717 */   "Haas-Laser GmbH & Co. KG",
    /* 718 */   "Niigata Electronic Instruments Co., Ltd.",
    /* 719 */   "Yokogawa Digital Computer Corporation",
    /* 720 */   "O.N. Electronic Co., Ltd.",
    /* 721 */   "Industrial Control Communication, Inc.",
    /* 722 */   "Reserved",
    /* 723 */   "Electrowave USA, Inc.",
    /* 724 */   "Industrial Network Controls, LLC",
    /* 725 */   "KDT Systems Co., Ltd.",
    /* 726 */   "SEFA Technology Inc.",
    /* 727 */   "Nippon POP Rivets and Fasteners Ltd.",
    /* 728 */   "Yamato Scale Co., Ltd.",
    /* 729 */   "Zener Electric",
    /* 730 */   "GSE Scale Systems",
    /* 731 */   "ISAS (Integrated Switchgear & Sys. Pty Ltd)",
    /* 732 */   "Beta LaserMike Limited",
    /* 733 */   "TOEI Electric Co., Ltd.",
    /* 734 */   "Reserved",
    /* 735 */   "Tang & Associates",
    /* 736 */   "RFID, Inc.",
    /* 737 */   "Adwin Corporation",
    /* 738 */   "Osaka Vacuum, Ltd.",
    /* 739 */   "A-Kyung Motion, Inc.",
    /* 740 */   "Camozzi S.P. A.",
    /* 741 */   "Crevis Co., LTD",
    /* 742 */   "Rice Lake Weighing Systems",
    /* 743 */   "Reserved",
    /* 744 */   "KEB Antriebstechnik GmbH",
    /* 745 */   "Hagiwara Electric Co., Ltd.",
    /* 746 */   "Glass Inc. International",
    /* 747 */   "EMCO Flow Systems",
    /* 748 */   "DVT Corporation",
    /* 749 */   "Woodward Governor",
    /* 750 */   "Mosaic Systems , Inc.",
    /* 751 */   "Laserline GmbH",
    /* 752 */   "COM-TEC, Inc.",
    /* 753 */   "Weed Instruments",
    /* 754 */   "Prof-face European Technology Center",
    /* 755 */   "Fuji Automation Co.,Ltd.",
    /* 756 */   "Matsutame Co., Ltd.",
    /* 757 */   "Hitachi Via Mechanics, Ltd.",
    /* 758 */   "Dainippon Screen Mfg. Co. Ltd.",
    /* 759 */   "Reserved",
    /* 760 */   "ABB Stotz Kontakt GmbH",
    /* 761 */   "Technical Marine Service",
    /* 762 */   "Advanced Automation Associates, Inc.",
    /* 763 */   "Baumer Ident GmbH",
    /* 764 */   "Tsubakimoto Chain Co.",
    /* 765 */   "Catox Co., Ltd.",
    /* 766 */   "Furukawa Co.,Ltd.",
    /* 767 */   "Active Power",
    /* 768 */   "CSIRO Mining Automation",
    /* 769 */   "Matrix Integrated Systems",
    /* 770 */   "Reserved",
    /* 771 */   "Stegmann, Inc.",
    /* 772 */   "TAE-Antriebstechnik GmbH",
    /* 773 */   "Electronic Solutions",
    /* 774 */   "Rocon L.L.C.",
    /* 775 */   "Dijitized Communications Inc.",
    /* 776 */   "Asahi Organic Chemicals Industry Co.,Ltd.",
    /* 777 */   "Hodensha",
    /* 778 */   "Harting, Inc. NA",
    /* 779 */   "Kuebler GmbH",
    /* 780 */   "Yamatake Corporation",
    /* 781 */   "JOEL",
    /* 782 */   "Yamatake Industrial Systems Co.,Ltd.",
    /* 783 */   "HAEHNE Elektronische Messgerate GmbH",
    /* 784 */   "Reserved",
    /* 785 */   "N. SCHLUMBERGER & CIE",
    /* 786 */   "Teijin Seiki Co., Ltd.",
    /* 787 */   "DAIKIN Industries, Ltd",
    /* 788 */   "RyuSyo Industrial Co., Ltd.",
    /* 789 */   "SAGINOMIYA SEISAKUSHO, INC.",
    /* 790 */   "Seishin Engineering Co., Ltd.",
    /* 791 */   "Japan Support System Ltd.",
    /* 792 */   "Decsys",
    /* 793 */   "Metronix Messgerate u. Elektronik GmbH",
    /* 794 */   "Ropex Industrie -Elektronik GmbH",
    /* 795 */   "Vaccon Company, Inc.",
    /* 796 */   "Siemens Energy & Automation, Inc.",
    /* 797 */   "Ten X Technology, Inc.",
    /* 798 */   "Reserved",
    /* 799 */   "Delta Power Electronics Center",
    /* 800 */   "Denker",
    /* 801 */   "Autonics Corporation",
    /* 802 */   "JFE Electronic Engineering Pty. Ltd.",
    /* 803 */   "ICP DAS Co., LTD",
    /* 804 */   "Electro-Sensors, Inc.",
    /* 805 */   "Digi International, Inc.",
    /* 806 */   "Texas Instruments",
    /* 807 */   "ADTEC Plasma Technology Co., Ltd",
    /* 808 */   "SICK AG",
    /* 809 */   "Ethernet Peripherals, Inc.",
    /* 810 */   "Animatics Corporation",
    /* 811 */   "Partlow",
    /* 812 */   "Reserved",
    /* 813 */   "SystemV. Inc.",
    /* 814 */   "Danaher Motion SRL",
    /* 815 */   "Reserved",
    /* 816 */   "Tesch GmbH & Co. KG",
    /* 817 */   "Advanced Electric Company, Inc.",
    /* 818 */   "Trend Controls Systems Ltd.",
    /* 819 */   "Guangzhou ZHIYUAN Electronic Co.,Ltd.",
    /* 820 */   "Mykrolis Corporation",
    /* 821 */   "Reserved",
    /* 822 */   "KK ICP",
    /* 823 */   "Takemoto Denki Corporation",
    /* 824 */   "The Montalvo Corporation",
    /* 825 */   "General Controls Sistemas Ltd.",
    /* 826 */   "LEONI Special Cables GmbH",
    /* 827 */   "Reserved",
    /* 828 */   "ONO SOKKI CO.,LTD.",
    /* 829 */   "Rockwell Samsung Automation"
};

const char *DevTypeStr[] = {
    /* 00 */    "Generic Device",
    /* 01 */    "-",
    /* 02 */    "AC Drive",
    /* 03 */    "-",
    /* 04 */    "-",
    /* 05 */    "-",
    /* 06 */    "Photoelectric Sensor",
    /* 07 */    "Discrete I/O",
    /* 08 */    "-",
    /* 09 */    "-",
    /* 10 */    "-",
    /* 11 */    "-",
    /* 12 */    "Communications Adapter",
    /* 13 */    "-",
    /* 14 */    "-",
    /* 15 */    "-",
    /* 16 */    "General Motion Controler",
    /* 17 */    "-",
    /* 18 */    "-",
    /* 19 */    "-",
    /* 20 */    "-",
    /* 21 */    "-",
    /* 22 */    "-",
    /* 23 */    "-",
    /* 24 */    "-",
    /* 25 */    "-",
    /* 26 */    "-",
    /* 27 */    "-",
    /* 28 */    "Capacitance Manometer"
    /*100 */    //"Weight Scale"
};

#endif /* dnmsd.h */

